---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: sonarr
spec:
  encryptedData:
    SONARR__AUTH__APIKEY: AgB93l+MDfHKoaB6M/DvnjZIbVnDAkAgoPfwgiOX6zFrSy0ju0/g+wzsNfiLWq8Bwj/iZTZzRgNN39nqX858u8eyN83ibFAjkwZugbU+CBY2Edp+qFgCWMVNh8vIWPxk68xIwkumXoPBi2yh9fMMhreN5klHVUbSohAgpZdsUR6eGZZR4uQk63JNYcWlGDTHBB5rWj0rHPX7UjOAx5MLdq4sXJ6lvw9gt+euZ2c2CMl4B1Aq2YtDnBCLJrV+9AASp89iVn4TYAbY1FBSOqu8KlhPWKmFcoVkiecnlXkdPLaQLGphcATSqdoHB+56e0iWOrfwhT3jHRSpXZ+FSKVr7tL92kaO4jRc7J4YyiU39b7XgGgvUexUcaWSpFNoyG3WLpefrRrx14+fMt7KNyXnUwcyZZnwxfCun8xHECIbp440pyHXwuz2jEUdJFjf3jMD9PIJPAlziYy2kRqdYFjNnyv21SibubsqDqY7XRKCq/Q0tfCrmFrUBATEG2+zPTsAiz/2D98m+6unuez/zFTXRbCHdjWVNSXEGlQm80DQm6iiLBO6n/IS/nc/I6TfUl1jHXvOfMgj8x06icpnoOR96FBoqSDg0SDzsH+ILdmL09XqAA0XxUsQdpCgeXnCLMGRsuMuh7nQt6nJhrcVJMrXUwtAr+AtKD2ju8ZAfK7/7eQm+benYmVygluNbNyDROL1uISou9/3zG8o4AMmUb/2V4xvLE81BPQWTlaToneTf1JlXg==
  template:
    metadata:
      name: arr-api-key
      namespace: sonarr
