apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: arr-api-key
  namespace: sonarr
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /sonarr/arr-api-key
  targets:
    - name: arr-api-key
      namespace: sonarr
      kind: Secret
      creationPolicy: Owner
