---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-api-key
  namespace: homepage
spec:
  encryptedData:
    ARGOCD_API_KEY: AgBLpqcd4XsDC8MXaKb2pxMl0hmN++MHbjWiVDgPRdfJIBStXg0klnvOjerdmRnQa5EsbmYG1lPmcnEjs4/gdCxEQPrLqtf+mCLCmfPm1xe8BJmO5ucLkqzP0HwBNc+9Wyi2RxgP64okNL/nv1etOfOw7oPsrVrfo2SB4i3anTi+DSAPr4shnqs6OJvKuogMsSx0vj93CG4v/uBcrXNL4fPrhiO8DgTO0yMmBgCFzcxpoKr4aFe5T4gw9yCUA83DPaStH/IQD2n1lkNavEh3iKP0YXHEFnMLB8kupx75hcFrc8ZcLBuM3uoaZLVBbJlFRkD8kSf2RgOSoSPMNzVMvdCDsjXpgwOxGNsYCDk72KwcCt65RAVa6rBxvDjEbM8NuSIcOQAN11aUzFKEKVbuCLH9WolZI+EBxyeS3JRvNJU1Gvwl3GK3vyIKfujXh5Auqy/Sg9G+KVeratIIXh6Pk6UeJW/0gTwM7t9ZzeBG9yseKSIkIbHITslU5dlt/PieZ2eIRnQ0vUNHHm6Xm1D1wiOPijpy5zds8iWvjr1i07yS20s6Ppzlgs7sBcOjAHmxq8bdNloS4SNjwbPZF2Jyuc02q/07H8WuOSecwn3WmWtcpjUldiqxJV0H5HDHq0nNU5czOhK5cyuhDggepbqNg7V6qRVnzO/kKJd6YeJLXeuRekJLd7QJbDdTmYVgfU1zra+SybPIr/jXC25OhNpBnJBhG38XKYkQx7XXLtwGrM6BHQiJiM2wGv7Cu2prpBU3/4w51fT9CuN5pPrrOl8BYxp0ysdeNwgbgpxFZ66nMvW3ZZw4mjvG3v1boHpxLH4LJthURfbGmKMsSCYb2d8RNEqc46z3wnV9LKHU416whnNKdaSiZcWyrB5RT3QOP9Ci77wKXIWDx+GC2sla6fnFycfdEOM9Be/vSJtn5fRVS2Q0nTEqA9iaxXaiYZkD6bgfVh0jtU42HVD9p720O5N//1KA1UXof3ajrIx/KMbI2FRFT3UznF6e0I/6e/TSPkC+jig=
  template:
    metadata:
      name: argocd-api-key
      namespace: homepage
