---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-keys
  namespace: homepage
spec:
  encryptedData:
    RADARR_API_KEY: AgBuflcUrOWx0F55txv2YBA+kW1vUxLOrmIyiOFc15TIBgKxA677fopXBvwIiTAuXbgkOmFd6TtqX5EBoxJDQhjC2K+LLgbwdV6RWG+v7MqJpVHA5BW2ukt33K4t4bVFLZ76oXqadfFIlXhAtsAMkU71p6eBlZjJoYtRv4d3Q7S2tnc6M4oI8bUVEcA044cOM0W8NUNPFOvO2+i7hQcZER/IXaypGyF8DMW+J1jhthAroVunauE4y1HLb3cUo7n2lwmaUgY/9kdXsjwyd6Xk6NNaqef8Jy5XK6euagE9vT+WioYDVORgOtxTFaZEE0s/DWHAJ4NdgZUOs0c9Do7cht4BIEYaXWpzu1rX47a+ImN8JWuIER+rhLXTNatwJhcqTVRvQtch+JHDvXKsvTYazELsHLziiheg68hszlHk93jgfba64xHHHoEEJA9GSiAhOdJzC4F4aJbFJ7Aa5A8TFvhCjKeb7lfJBwC9mGnAm9DpYeqGBgLhAtWFMD3CxLIPXZflRbTCZEB8+BjjQnudnMsQU51i6CUVYKpaciJpi4HM7VmsoI+iETCDY7401PnPwAYNxbwT83y3vFmbse2kf1JghivcXlLwFJP7wLMT8+Ol2dF99cdNzZv6ARenuJVIizHcmCUT6rdNX8lyMKcWU9GCd5xhKFbsOcRk6o34T7Q6jdrXaUYowQRu9gXXoJsXddMqrjzTJ1m1vnShJWbvZNox85aGSIA2WdrPBZibN6o/Mw==
    SONARR_API_KEY: AgB4wX1Cq5718Z4bsM6jI1T00x03KNeE/MtWtvxQQ04Zjgf+9FQFmNQ4Ut+pWJZATy7jcNn8ke6qM7Db298h6f0+eaaSk9fquiIA80BBXEa30oMPG7yNMYq8FXwx8HQnnzRrHVAmpAyVx6CAGplgBYPJ7PuzPaM+mRbE9kXLNnKILC01zNQ6ds/85jSy1sI0t6MxcpGf5Nk1REJc4GxIrHMu/ElaXfvqEl2N3VAex5nbwY7eY6F96YsKIpg41A7RHc/F0rtAK1/iVUdKPD2LcmEwrn9b9ywVZGccMLz+8Wyy4g4bS1AuYFAw3hw4jPozcsZzKSVTJR27Znrjdu8SMJBo9OW4q8dehlCnCpJ4NwcI25NVybkF4hZratHDsSDOnKqC1D7msrc5VotqxOv0HlghnA5lbzpFeESxBbWwF4z0Whz8x1wwyexL91fJpq5hFlFdSSYQSiZR1FWSlSsoTg8iJAJ7pFj0AwddpUszp3QnnB4E9nUdlH6Fq4y5UuPZyFjJIIqAgyj47wRmQQ+TbiS4uLKVywVyVwxnmfWuTX/MnOR2jRBSs5IntUdAisGMgCrW8AXAkw67LoRV+0NVRExC1t8BkBCSS422wjDmSvDmn6uzrIkybZerUVxkTTqCyN+UhO673KWAn5h9lRXaqbmDkoRa00SLGuzWOJQWWgO7g1TBoElU/nuEi+sEeebrHUvFk7lLPG2cpq92bkQJlnNI/rYc1NEk63XsJnexgMqTkw==
  template:
    metadata:
      name: arr-api-keys
      namespace: homepage
