---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-api-key
  namespace: homepage
spec:
  encryptedData:
    IMMICH_API_KEY: AgBTrVznRrdZ5r9ONaZb1XlSn1adOHgzjE8ULHJGcIxw9WNmA8E0WTFmCe9KUmKvH5wzlT+oq+qEuAudTgk0BZ+JPGYamuZvG+uvTmkx9zJe/kygsF3gIS7dTj9XJ6T+OL9XV3K4YYsXD9mj0xWiJEBvoTXhvYsZf9M9b91PzPrVnO3NSIwgGx8vAuOFymDIXwroOoIMFQ7gVFkT3d8XqaWEhXEFafpnPvi3uCLTLYDHYQV8w9cj6IyjI3twbS5fj6OQ6YxziuLb/MfAZfchL7TwhjK90C9I7u5lTxyEFO+64Dp0i0eoRQWMRoESzlNeIj2hnABsMY21lTOfKv+imBxEn0Mv8T/4FSDOYUQdQez+7a6FPh/SDbes2M5jALTQjtpu1XSO38fl9xdz7+FloIVhoBPq0d0Q8o8Ie3h/QXe31zxFmbQZPrXoa6T8EnBiHyO6t9dVfayNf8s3m4ZZVSvEcwq1ux+hRWmXMfeeWSuJNcAPh4hcCDViP5iEPHSyIrWqSRCSaWYgkEhShEhV0dgIen14XsjNVDifR0OrRJ0vTH0JxQckBA0y72WZf+GUqjCRH7CXn0HzOufehle/rphC+i5ZKccYVM+8U6kTZRcZQINAmAy9c2RSJUB5TImOgAXu2q8UekdQhFnUuVwTubRT4Kd3vQGozTANPRcpwqtosfzi3LSerkq1xPSKrlxiUfjNbvtmX9K2gmqF4r8BJ4kt+1Rgh/VSo+TMED2ZYHkBzR1EZhM1PGDcHQ==
  template:
    metadata:
      name: immich-api-key
      namespace: homepage
