apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: arr-api-keys
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/arr-api-keys
  targets:
    - name: arr-api-keys
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: navidrome-homepage-token
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/navidrome-homepage-token
  targets:
    - name: navidrome-homepage-token
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: immich-api-key
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/immich-api-key
  targets:
    - name: immich-api-key
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: jellyfin-api-key
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/jellyfin-api-key
  targets:
    - name: jellyfin-api-key
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: qbittorrent-local-creds
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/qbittorrent-local-creds
  targets:
    - name: qbittorrent-local-creds
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: qbittorrent-seedbox
  namespace: homepage
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /homepage/qbittorrent-seedbox
  targets:
    - name: qbittorrent-seedbox
      namespace: homepage
      kind: Secret
      creationPolicy: Owner
