---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-api-key
  namespace: homepage
spec:
  encryptedData:
    JELLYFIN_API_KEY: AgAK3+td4sPaB3Sd5iP9tcNn3pCCURHKdId/WmPEAGq7X19KD6T8E6F6sPrhWDSQv6RBaHRHwph/3VueRnae3XOmNmRNL3779cEwwVMrpdrtxzSvBqJ7rLfuAg5PgolDHJArwENAPs/Xd65ZB+JABNLacw1dXzsgt73nIe1yGZkkStMHCQK/F20RpndYJfPB2RVqBMGl72XzByFB4+ENGw5N/VCHxUFb50egHN67Q0FaXAn4wc9/JiMmwSCjmjDPmGzJrNa9yktlXRq+CYyIeFvKcJKWZIwYUkoWzAI5Ri4BjqZrYir51/g9IDPn2Ltgepv0sg3CKuNugiMe1WBV/vFz/ar557v43oFEA4XncWMPbtGeJr3Kt2qwn2ccO/7fjpVEbL6bWBVNTwn3CE0PordnUNITKyv39ebWDR54rAFrnM+Z7a7XDb7l02g5sVigNyPzfPQxNyWHv7VnzTHuE+B/zXceCAp0ErfGQPDyZpMgTTImpFPCXQ+JVrIJrU9MPNlgzKKcVFgT/0mndf1tanEbsspb9d6jtK8FUXBbRNLXH0KU1d4Fvr8oTcKkMsNsCVZQjrC2eKLJb3O0b+1feIjyy0f5D9g/N8L5iH23Tinj5j7TqfPGtorHVTL7ykS5xNbTXIivAd/3FOusT6DtJyvOhhAP1cST6NHDtuM6ZA8awd/7VU+G5p4CZ5d1ddEU33OvQrF3xRgI7I5tV1LAowlAJhaMiTPp2Wp1bUucWIw7wg==
  template:
    metadata:
      name: jellyfin-api-key
      namespace: homepage
