enableRbac: true
serviceAccount:
  create: true

config:
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: boxed
    target: _blank

  kubernetes.yaml: |
    mode: cluster

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - greeting:
        text_size: xl
        text: Homelab

  bookmarks.yaml: |
    []
