apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: homepage
  namespace: homepage
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
