apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: ntfy-webhook-url
  namespace: monitoring-system
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /monitoring-system
  targets:
    - name: ntfy-webhook-url
      namespace: monitoring-system
      kind: Secret
      creationPolicy: Owner
