apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /cert-manager/cloudflare-api-token
  targets:
    - name: cloudflare-api-token
      namespace: cert-manager
      kind: Secret
      creationPolicy: Owner
