apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /vaultwarden/vaultwarden-admin-token
  targets:
    - name: vaultwarden-admin-token
      namespace: vaultwarden
      kind: Secret
      creationPolicy: Owner
