apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-nfs
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
