controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/media: "true"
      tolerations:
        - key: homelab.io/media
          operator: Equal
          value: "true"
          effect: PreferNoSchedule
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/jellyfin
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/Los_Angeles
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: "4"

service:
  main:
    controller: main
    ports:
      http:
        port: 8096

route:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Jellyfin"
      gethomepage.dev/description: "Media server"
      gethomepage.dev/group: "Media"
      gethomepage.dev/icon: "jellyfin.png"
      gethomepage.dev/href: "https://jellyfin.nik-homelab.dev"
    enabled: true
    kind: HTTPRoute
    hostnames:
      - jellyfin.nik-homelab.dev
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs
    size: 10Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /config
  data:
    type: nfs
    server: 192.168.30.194
    path: /mnt/storage
    globalMounts:
      - path: /data
        readOnly: true
