apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: unpackerr-api-keys
  namespace: unpackerr
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /unpackerr/unpackerr-api-keys
  targets:
    - name: unpackerr-api-keys
      namespace: unpackerr
      kind: Secret
      creationPolicy: Owner
