---
- name: Install k3s server
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="{{ k3s_server_args }}" sh -
  become: yes
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s to be ready
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 60

- name: Fetch node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  become: yes
  register: k3s_token

- name: Set token fact
  set_fact:
    k3s_node_token: "{{ k3s_token.content | b64decode | trim }}"
