---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-seedbox-sftp
  namespace: rclone-seedbox
spec:
  encryptedData:
    RCLONE_CONFIG_SEEDBOX_PASS: AgBjZfTQQExdfjh7thA2d0Uhj3FeCMO+qkyXq5Yk5ZU2JQ9+R0UYlv4NYuu6qq/1EAurhpVU0IXwLSVx8q2luhzsd7vDN6zhY5lBkjWbkzrLNtp9p7um4nOfO4ioLFVCSoT6Z7ODR3pepCXsIDZnEcK/anJw9c5we9IB0BYtVmFvipdbL1RoJ1V47djrkFwSVlZYPTlowYbpgQA0mLznzEgDrBuCDWAqaDKGs+pPThoSYcFG3LnYjA+PJKb1ndn1A83JR5g/EJegLmSSZwwmHXWIlt1gsxa9jqZ47elWQW2SB2PoaSap+GYivx+xI0IsK/lTTPAuqKmTkraOCFWfos8iGDo6tyLV0rPuk97KGitNUztJP973yu64lh4FaVhjjxBn4SMFlX/xP6mRYo7hn9sPgIA9CWGUxDXRAWqfm9Plt/YrxJKH+S9f4Tfssz8dv/ooCBOHJ0+rOBLSBxryzFo7ktZG4JhFraDCbE587upIBh2dLywKQIQhSvKm+XAt2Ykb5D0nPmvVmrGwAlgXqPyinRp3CrANL1+VDpV+94LxxZZwMBMa/8f+yl30e50o6WK08FFiwfJBV6iQJg2yo4IfIoao26YAtqK9nkk4gC+2Le6kg8RzPUAeRdaw9Z85ghN4j1PVoKjwY+6+20ec7Zgu+nEgTz86EItM/BaLfbR6Q0jyBz5wW0SIWqsDFmtNLWV5PcJbs1ONRaezbQjFH3jAmOa96lWZ0iMC+4QhyAWDEXVm
    RCLONE_CONFIG_SEEDBOX_USER: AgAc2ZHVpfpLbxClEim6RJfYtfnavP5hAzrtFHAWwi8bjZvpmduJWXe+HkOXGwqNE3mezarpyOFtOvl7rWmaBvNHmIwFAbpbLrTtQG557sglqbP9RYNDiocDludthaH6g9+YGlaVJU9XOe9VdWVZMJ9IN2OYp5HBp4Potu7aEVjI/fwguRDW9rrQDnrO0M89LOtsmmwz0CcD9ef0AYGxe8l/810H9j8vaTgQgUompOuM6rUsPitzAaswmfW766MLwVU5+7W3Z+DtOaAevYooDl4H+Bw73gpiQT1I2z4xd8C7K/K0qd46KG95IJzWcRlFGfRcokitdkE8/MBvPIacWfhQI6cMfeYAIjEx1cE4pydZOjAm+mUZL9H5k5qlMjkHROCtCLhOVhqTz/6yFJrAzstA1SFpNi0eDzcisYh1AV79SbFTSq4KFyxAkRzztmkntH1UGqXflzMBP29WedZuZYEMHJJEdKot6ft+r/l1UyxDksa8ZhvM+cCYNoOpmPCdpQNDFazeE/uytWufkIzofMBM2ozakOnjVePrDUoFUFAYJtmeATG4aGj94FYajYdEvwh6Azcvo22wEcLFFKasdzHFvdaAsqasCqwfU3OSdQmMDSfo3JgvEK4ubNysr57PTHl5bJWOxqICROBkpQmWeGc5mpTnIKNFVZbNscqHPdZAA9a3AQUW1R+bn69nVhwEvhUC7UUtL3OMkQg=
  template:
    metadata:
      name: rclone-seedbox-sftp
      namespace: rclone-seedbox
