apiVersion: v1
kind: LimitRange
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
