controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/storage: "true"
    containers:
      app:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: latest
        env:
          TZ: America/Los_Angeles
          LOG_LEVEL: info
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 1Gi

service:
  main:
    controller: main
    ports:
      http:
        port: 8191
