---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: radarr
spec:
  encryptedData:
    RADARR__AUTH__APIKEY: AgCIdx56QE+faSXBz4YORHUVMbHtjSDVzbyNY3Xy/0S0hX47HgIb//g6cOK7t7YMcw6YXH55s0YTO6Ul963tBXqv9RJkZt0lzhdTkziAbiQhm53RqSqUaAC4YZLIpwc1VgJsBx0Bq9EnFUg6PgIvSTFpol2l2CUF2bhuc6VWmimBc/nJuEU4VKVp8h3zXyBdDAAOdpTPqITtsf7qEwvT/fF0EaA3DqAlzyNyzrVZO4uQHxKOCmYBtn6RNevdWHSbIbwj/gabYljA3Q5o7PlRW4mhegutmFW+Q9JGitdqmva81J3QDTW3xAssE/P9v58goasGJNtJ+IQc2Qbi4AC7Ymy3DBKVakifDNLCIpNEFdjWd5YIvR4KMaeR1Rm4hRIJNdgWTay/nOXWHCOazC7of1AlaYrVmFTuC2i07EiBWp6VyuZtUPspEUrPE7R6gRSGNHEpBvDrhtFUfNKB39JSOxRepEp/BukOh2DF7b63qv7b+y3imHZilO0LGA61YKa3FdHt8UGANCllc1vRgPf1TswXk5gNBzOkRfYRwqFAi9gqJtH4zBk2cxp06plkx0O3zUw1wZQxiNTrdqThBEyRJVcQBt9JckVD0elwofGFRig4MP8gBGTD+WWf9PfqI+gTMdn07N40drQwmzQiiV0IiPr4j3FBFGmfJXEVZfdZ2BldlaCg7mnrIdWoMxDNwBgm7rCiD8eHWDfdLuOih3XoAyaoiN2BqE9jvXfq2toQJsF1cg==
  template:
    metadata:
      name: arr-api-key
      namespace: radarr
