---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: radarr
spec:
  encryptedData:
    RADARR__AUTH__APIKEY: AgCGDZ9wnzFeEdeakHHQZWOGyNSFbz3jmyCsKSiAe5chwsg37UARf+ej4YybVLd8GJVw+RBwRSa3YHpZkNHbSskMCeA+fuFszSAGcp5NpN5IheJRBFIgqawXq1YOsV0ReA7AxbgB/RY5MVkMBZ+E1ugDjiudkvHc4aZGDCnr8NlqEGZiwPXm9Kd+Fs1ycTWzdtEmxbDZdbK2WhpUFIqSawTIKiFe4903NBgGT9pPsQ6AXJjtpV0418MPMb/cygfGkFaUHlW1CfKpjkoB4VZ1BWDf7KxVtMOAqCTpG0h3KgFYGvUR9h7osHKbnpQ1+KMQtd4UKkX+Ek7M0/5+L5Ysc1NoiIqhTYfNG3PplWOmGMgrjFkQxqqUn1/2xgxHMVi9paAAWTJ9+5qq5FblIdDyModQkdyYC3eSSsbZscID0xbFhuaq20reSXr92webyMJkOsRkaudwa6B3pyml43E7ozceQxjZYcdzWWGzmBqNPjT695moi/zNA+2DgnOqkY/o199+kjnyjhqmNLGqzxaYa3zDKsmO/UmiH9o8XUNRNTI95GhDgf2CgPRWHRm1fS5PXE/glMl5ibpA1oEukkKhkaszePfoX1MIyDQS0C5ez0Eft2sx6YQIATlWY+KSNV+IV6Ptk8EC6sLhVR0VWUwHBg1gp9HYmiCg8trJerTmrVewEOwSufPth1mkKx468wVIMLixdP01v0uNOppXOBPN4fW+uMsMy+n77W6LWxs2Xd0M2g==
  template:
    metadata:
      name: arr-api-key
      namespace: radarr
