controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/storage: "true"
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/Los_Angeles
        envFrom:
          - secretRef:
              name: arr-api-key

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

route:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Radarr"
      gethomepage.dev/description: "Movies"
      gethomepage.dev/group: "Media"
      gethomepage.dev/icon: "radarr.png"
      gethomepage.dev/href: "https://radarr.nik-homelab.dev"
    enabled: true
    kind: HTTPRoute
    hostnames:
      - radarr.nik-homelab.dev
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 2Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  data:
    type: nfs
    server: 192.168.30.194
    path: /mnt/storage
    globalMounts:
      - path: /data
