---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-api-keys
  namespace: recyclarr
spec:
  encryptedData:
    RADARR_API_KEY: AgCGrv+erf9UQiktNPy/lk86jdcKOCPzxG+qQqP41EV3ZsNV9cCbOc/kOTuTdVtjaZkuVFHNVA20hboEO1irA8X3uFUYJIPvUTaKXzUVny5MyV2N569KvZrJ2os+a7ONwnyLu4rW5suGNAvDrPhGtSv8/20uck0iLnozwhxerF3R0rKqqrvFJhu8c8w7jR1DggsmqgwoLjeV+sn51lyMczTqBdPEe+vrSxLFmcNt9MDR0YAnlXYkr9Zv0wJkNfDbsY/PQj62wZpate9IvSugPytGFiQ6KGQoVfzhPVfijfldHr1GOXr5ATpx91F2wmXCB9Cv7XDgWMJULCk6LObAd+H831F7pZYZwGqEzx6df0IZ0R4VrRbb5eBriBnhizgoIhGA6eEDyaPEzUtGewmrVvXlsvh61s99qUe+qteZfcxZToPTl2Psx9Wxq8x5KD676lVH80bAagZ6Zf5GCtc4Tay5+RjhESO3t3r3LfYfdl17QySVKwLf6LBzGj5NiJnW1AWpqYmPrxrAz1F/gm33JvDppMK4scFbOo1vQfelhuPVYX1L3j/Pmt5Cu6uUe8LKaOfmd3vEVWdUdJXG0jN4NNrMQEEENDnJWOA/AO/jSeyj/nlCiV6/bnbuU91H8jhDYLliqQKLmGdVWyIdOeVpqmntXayJxVh6lP1kYDQasYpVbGXj0iL9AicX31FPRohkG8fs9V5sqXom9Jf0G+HLEygn/fMxHwYNSHNyqMZ/o/5eUg==
    SONARR_API_KEY: AgAhryHcFEGHsz47LB1vvodmnZTjCf3C4ICebAaB8Bm0+GGHzWOeIn6JLxK6OVnUs4ZJxhD7RLe0WCZOC9he1hr+4qsd5unHawcreQ+FcjxMPiHhbRQDU9o0QltTxbRmOlrvjYVgNORJ79k3S0bioGsAp3lJvdRr73QEAEB/2auTU3uo6QTqESa17xWvs3arLj1Jef+8RH4GmFYHjMp41PL2f+8vcAcxXBiJmJKx6YMTaqXbbYs9KlcwEKk9WMvtTzczyhhS3G25KK72okV3nPYjMwW1T0ui191rZ6vkEeownlJ5vZ1M719aG6/EwLnVl6HPRK8jLy6KJqM3F0cy3RK7lcurwqzHmlIC0q7AHYmEDgKgB+r2sihmp8qgiT6QdcU9qY0u51TW41HETUByqySb76XRQ9q+klR5gqdvWXUVtNhfOhVc/W/ElnT+lMVTn+Y8LkaRoi1jndRUjIPhJ5RfIxVZCFDBrvl1yjqugM3JVVzlytAZOEzu3qwK39gA8351WwrW+FPAqoUxomgSpi/I6XDAGhgp6GLc6MD984CsJP5fK48pF54J/Nar0EgFFMFeWNzIPqqO+b9gnEm83pgHHoq8p0MNpLtSIQ3AdYSMVxyfClIOUnRfk48GhP37tOOi7jtuJx/msI0HmvRSA+fGPvx3h37br4olImu26wEEAqJ59Md4e4PMfB4dD5TTBYyQ1luEfeqb6iRzzWHNP+IK8JFutZlR/OguB5SEzVdeeA==
  template:
    metadata:
      name: recyclarr-api-keys
      namespace: recyclarr
