---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-api-keys
  namespace: recyclarr
spec:
  encryptedData:
    RADARR_API_KEY: AgBceuLQfT9cs7bpbqEa2CqUzua/sOnwHxhTDRFyKq3fZ7HoPYll0t2373cd9+untB7JVUDTqB6werHJAOOPxypLqPC3wujvPNXuFJcmM4o/LMyhjxan3P3xG98Ob1meOs9O0C+YulVhzUGLOG7f9k1c+eCTyJzLtBB/koJR1U5up6cx6nXAv/DcCHxPk/t1TNiHy0J/v9gZjPfnAGt026mBg8GA78HxY4BvkCIdYp7RO2PMHnCseV3QNzYdghd2TT6kgpLoONzIMVfVYJthiaqjyAfC0yrcKum3r2UGZLEvDKE7hdHhBR1NOM9YEoZpQann5E/Bd8usk1LD4RgJ5LWY1ziZBAm4mDq+4zS8qkFGsV7eETisApJLzjknn2Z37mBCD/nUUCy/wZoW+/oJawtOLWJ0iX7yQcxJ4XC6P1RIve+r4z8L/mpazk5kHwPkbJoSLmYqWx1L96bTM0ZJCovrDirNTwi348s8FkSbIVJnrBNBIa1KLUE9pSou08z+HN1bZv5hX+0wU3BSSJemwdTa/5c+IwOE6DLZCEl9gGOy1tzwEpMVRf9dZ7MO7oXAvHVktcRfXoWsRDWjKKLypSafeFhw7M2A/lZfw1awxyqztIGVKO5AdXg+TlSUJGSD4+W7m2BWX4q2sFuqGgNQLeh8a/wwu5DU0/Di1TYrSN4vTSckpgQbuMyc+SiV/ePrl3WRPx3WSbe9BZrG71ZtjfL8ymE1Sxu9+2UMSDmmeouK2g==
    SONARR_API_KEY: AgCVNEQb7ybntzGT0MIt/tA0RSCzuf2sq5NfKQF8ZICyi+xaoJ+eZWFjcjlMTnNPkOUEn5pOQiu0DEGAHcaagLEb5Xk98x2REQuHzjkiBaeRBoAqzyAMJV5CO0Bq0LD2a9fi18ViTs6qaKwpjasALLrXuP9sp4HIvg81D4kAYQ8KXKIfMoCzGGCz7GKkvlqJM7vtX6tVPzMxB41adkUne58n5JxNDcc+TP8mx2MeABzS1YI29NRJVfXSOz8Y4RuoAil0fjYNmhXLyjWahbUz6UoayaFOgmGhCnbJXcJOBzhrTZzUVuhGUNEzGwhqzrUSxpU2Cm+olMYS7HYdYK6M76wDQEjZKrs0MEOh/x9e6YUNtVJJ8gtwHAbFHp/2VqEgTBmJ8Iq9I9a0SHTEo1TOiBBofG5hO+KOX4Pk8eFOPy0bFztlZVw073HlR+8zQwsj1YOYzWsInmF7tsl+EAN6rrs6ZfPba5SvjaWskscduKQ9ZOX1FHDF6i6LxYQhPofEobYJ8aVxt+pUutEEstPIt5VC4fLpFMYTItK/CO9NNT1Yl9MrOks/VZ4u2QywKl7A8i9Mz1hdFc/gLbNpO4tz3KF7/hFA6IWly3eFdIQ6CAU3V/DCTsjuRfiL8lmtTAx2Gn94xTjtu8+9Prn4z18lDhPJNWYCTBoVZuQgKcJ2boBYXANeBQNxrVhTlRnVB9oLDxmWPgfwRV2f7yIJEOYAyecQbYPE/9YRbPrcNLaMdB5SOA==
  template:
    metadata:
      name: recyclarr-api-keys
      namespace: recyclarr
