apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: recyclarr-api-keys
  namespace: recyclarr
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /recyclarr/recyclarr-api-keys
  targets:
    - name: recyclarr-api-keys
      namespace: recyclarr
      kind: Secret
      creationPolicy: Owner
