controllers:
  main:
    type: cronjob
    cronjob:
      schedule: "0 4 * * *"
    pod:
      nodeSelector:
        homelab.io/media: "true"
      tolerations:
        - key: homelab.io/media
          operator: Equal
          value: "true"
          effect: PreferNoSchedule
    containers:
      app:
        # renovate: datasource=docker depName=ghcr.io/recyclarr/recyclarr
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.7.1
        args: ["sync"]
        env:
          TZ: America/Los_Angeles
        envFrom:
          - secretRef:
              name: recyclarr-api-keys

configMaps:
  config:
    data:
      recyclarr.yml: |
        sonarr:
          main:
            base_url: http://sonarr.sonarr.svc.cluster.local:8989
            api_key: !env_var SONARR_API_KEY
            quality_definition:
              type: series
            quality_profiles:
              - name: Any
                reset_unmatched_scores:
                  enabled: true
                upgrade:
                  allowed: true
                  until_quality: Bluray-1080p
                  until_score: 10000
                min_format_score: 0
                score_set: default

        radarr:
          main:
            base_url: http://radarr.radarr.svc.cluster.local:7878
            api_key: !env_var RADARR_API_KEY
            quality_definition:
              type: movie
            quality_profiles:
              - name: Any
                reset_unmatched_scores:
                  enabled: true
                upgrade:
                  allowed: true
                  until_quality: Bluray-1080p
                  until_score: 10000
                min_format_score: 0
                score_set: default

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: nfs
    size: 1Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /config
  recyclarr-yml:
    type: configMap
    identifier: config
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
