---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: lidarr
spec:
  encryptedData:
    LIDARR__AUTH__APIKEY: AgAMuFi/xCnwGPGiFTJfKINtsxlBJ2pBM8CfPH6iS3Fh962Tqq0YSQ+QREDPtUwUaFipmmfdsuZkOeBsW7H8yrsR7KosB0pn0qPVS0vGzMDWE4c1QDCXsGG+TkbYJF4uZ1Xnb8/5BH42pyPj5SrIAHlnSdG0cpCUTa1yriAwXzMwuCXTbAcm3jAGSiimtHJxYZj3I/cWcUFXU060kSnhX/1WwJy1AOW7b4L8KNUi+f7wWcTL6zoGCLlRnxJyS6pKhzu4xjDffP7ib4lUyzOt6gCzLbV+OsQd+HJVIPjSO4ZKbCLOTR7jIyimV6ksfAkd62kdppnrV/8kTPgxwNihC3pPRzuRsTdBMJv+sK6zg+FdThDyhzbSvQud1pEDCCCeu7um/vhpEzXTFPeZufRFJ4a7Bj/xaBJIasnPfOLWlKYL9XtWq3BAJ/Kz3Gh/t5engfIPAS7NKCjutbRq9Zzl4pboRMqsq7iRGbfVRIGyTMzTcq6ac9eHPJX6FWLCJpDzY7HM+r69l2gTPiheQ0CC+aBHL8usm0bD1OuQc+NUuI5GXsT2YjwMb008jp9ug7YW+q/gK3ZE2mM8Ef1eneAa/ZX8BHatp44v0xutq0jRraJY4ZCKp1iOmB5Av+6B0ZC769hxnhm9A5fq1OZuDSNvbbNU/pXDOJ3tsq/RSTCr6NppS/fKzACdREwMLlnHRXNrKXUdrb8CVNn/5lcG5bd88qhtvQrxfLi1xU3G2K378oFY/Q==
  template:
    metadata:
      name: arr-api-key
      namespace: lidarr
