all:
  children:
    k3s_server:
      hosts:
        # control-plane-01:
        #   ansible_host: 100.x.x.x
    k3s_agents:
      hosts:
        worker-01:
          ansible_host: 100.107.51.48
  vars:
    ansible_user: homelab
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
