---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAdLKxbUMCPeKUdBi204z8yw+mfHNxomJhl8INYVbIrQrZW2NZElvO94iNuzPiZTbRCYkGdIvPNrYTuEeFmeIdnVOOJJP6N9Cr5IqFYZknYQ++llFEIQroQq2Yd4WsA2tLjII1IcLNy517GUbALdNDjrvqvV8ohCmD6CpmqxCSnCV5lZh3HdfCa1yNyIbeyp7iD3PA42lYHAF4nell61+WKWNsk57oq+NkQgvhuEDbTXNRDSf5Ww+DXof8yI9DMYCrq2V5T1CBxKIDtBm+eap9VElW+FuFuYvtzUeKLz3I6LaQQmaz/glo6ZoErwBcuVqHTFT35VNHQzGXVW9pY62xhy7WENP2t8QuFjoXgPTUYp96fPWYf6ZIErzmNYNq1OJbrJCSr3nt93Iz0KtA+fnLfVuExulzx1M9kYxxHwvRtf+q5vcbGsDqZZhcg0Xm0N1gG/ib63hXXboM0EpddY/4LjUXDnSX0d+AbUXMy5shQuUSKzq/1qvS+JThRcHgNcpD4GSiq67BzZiM5h87mtJh+ye7+Hj/Pwhb7bbbYW/650lzYMdt/npwYTf6nZFsz3f664N1mL5+JttrCk/NZ02xS8KCZekTRTcXGhjkMmWQwysCx+wUE2kNHs9JXbpxahH+Uf2WiRv6un3EuPri1pOdbnlxRbslv7YbOM6J0IHCD66uZ0EQ04eif4RfOxilB3TP5WcD1b1Smb3G2xjRG17gri7mcZ2ExTinM6nlj+sWCgA==
    username: AgCB/1NdqEqEt+CiWXyEs1OopbFvYyDLxDsU1GlpyAU2HC6RUXXV+Vj3shREo5gYoKTbWU5v8d8c2nFU8Aes7aVcI8NxA0dhkHMKtN+XPv79C83vWw+q8sRRFIS4txFdEqodljwY61F76mL/jHWG+rhejakLtC7W/eYXkZVfXsjiiT+knUdwqS9/AKXrAdqOZFhYn4rEaFx91k0BbnQlMnPaBsHBRIbbDYwND1z3pl4BLYbNZbP6eryw7BWIh6LjKgfmpl7jCtAUJvv0pvg+3AxMWrkI0eqYUvuzWW6mAj286uXJajGTEExhz0sZQbSpgn5Osk/KiBT5g1XuyZfJulgPeBtAlMMsfgmWXXmdALEltfDbpHDmJl7+2iqmEFsWycoenieqRO4nCrD6c2QtHYfamSs1ogt0Xzr2j6v2aNaC67YVs5HbRFE7/UcwjY8UtApZEwz2cNo4i7InxkyG6atJrSiuSeMy+2zWAgBi7jqTMIl4i72yWz9T2p7mdhLk/F9ywfh/1Wx9KS2wAQXvOIZNRHnjBMF+DfXsVZ6yEL0uWM3qipouh3PsYVWGV8WsGOx2dCQEZ+4Leyb0CDuxNWCwm7/o4/x0FFPiOcBKPWz6HggQ3isQIiC1BxFPOXL9n/1mrflO3ogj1nKzorg+Nth094ulvbQSQODHSoOTjPDNNiAo1eHeqTsCQVtB1jvOIhdMUhGjBw==
  template:
    metadata:
      name: nextcloud-admin
      namespace: nextcloud
