apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /nextcloud/nextcloud-admin
  targets:
    - name: nextcloud-admin
      namespace: nextcloud
      kind: Secret
      creationPolicy: Owner
