apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: renovate-env
  namespace: renovate
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /renovate/renovate-env
  targets:
    - name: renovate-env
      namespace: renovate
      kind: Secret
      creationPolicy: Owner
