apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.30.194
    path: /mnt/storage/photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 500Gi
