apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie

  storage:
    size: 20Gi
    storageClass: local-path

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 2Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  name: app
  owner: app
  cluster:
    name: immich-database
  extensions:
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
