---
# k3s-ansible configuration
# https://github.com/k3s-io/k3s-ansible

k3s_version: "v1.36.3+k3s1"
token: "{{ vault_k3s_token }}"  # store in ansible-vault or pass via -e
api_endpoint: "192.168.30.129"

common_server_flags: >-
  --disable traefik
  --disable servicelb
  --disable metrics-server
  --flannel-backend=none
  --disable-network-policy
  --write-kubeconfig-mode=644
  --resolv-conf /run/systemd/resolve/resolv.conf

extra_server_args: "--node-taint node-role.kubernetes.io/control-plane=:NoSchedule {{ common_server_flags }}"

extra_agent_args: ""

letsencrypt_email: "nik.gibson0@gmail.com"
