---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: prowlarr
spec:
  encryptedData:
    PROWLARR__AUTH__APIKEY: AgCJD45zeJPE3tLMZexmWOOB054Za88O6tVKIwqkk+Xq/6hTyy0uG5qc69dgZlOi0fx9T3zIqgbPF917Z1Ill7PSKsXF2ikVMQumsXRZZdnm1aX4FiZwjjQYzKGPkl20QCOy0hsLPug+On3/0C1j2vmi+/Ng2gGZ1JhX0QmEq+T1uE5GSovJMSSbAkNaXZOXAORB4dFKYknSPxSD97qacdijcGN6gfJMRrFAMzoFCJByTpndbkPS3FeXl6dzWOeDv7xKDppdNRA6rlk1xZYY24eqPbFRkRprrYU8d5HpTEhjUNGpUmEmyfbwGe3uKG4yEN78bVlNdSnGJscke42rW1ArNIn07TIijj13RyoOYqm7u2j9nR79iR08d7oJXCKY3ko00yWzmyjTdb0f5RV7t4H8QJ4ZCPQhhhcLviczDCziDhraQTw74xhrNaANYQRuRpBMf+fFwENnfQOGoiqI0V3NKSEPI0TXBooWso+fC41jS6a9w3HvJEV8rHH6bC2Bkc11Hvrsp60Y9PEUGlMR/6k7tdQ/TPQZEE5KzjpL8REHsZeWohcyOi7ZvXySml5AT9iGpZigtXVYZZ8D3M81LUnOaJ2fHH67K5togZvBtTxtg/J3GF20aGXwnlafoBBhHdGzzGRFxO6SXCH/2dAhsr5jhqFbQHCLF7Mb2TNaXHREAdvoLFo7Qwv8WjeammhJAkKWa7uyi18kzzOPM/Pue7t4UouvG1Ktgmar470JT+btMQ==
  template:
    metadata:
      name: arr-api-key
      namespace: prowlarr
