controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/storage: "true"
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/Los_Angeles
        envFrom:
          - secretRef:
              name: arr-api-key

service:
  main:
    controller: main
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Prowlarr"
      gethomepage.dev/description: "Indexer manager"
      gethomepage.dev/group: "Media"
      gethomepage.dev/icon: "prowlarr.png"
      gethomepage.dev/href: "https://prowlarr.nik-homelab.dev"
    ports:
      http:
        port: 9696

route:
  main:
    enabled: true
    kind: HTTPRoute
    hostnames:
      - prowlarr.nik-homelab.dev
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 1Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
