controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/storage: "true"
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/bazarr
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/Los_Angeles

service:
  main:
    controller: main
    ports:
      http:
        port: 6767

route:
  main:
    enabled: true
    kind: HTTPRoute
    hostnames:
      - bazarr.nik-homelab.dev
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 2Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  media:
    type: nfs
    server: 192.168.30.194
    path: /mnt/storage/media
    globalMounts:
      - path: /media
