---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-vpn-creds
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCS5NVb839hYSjMo6NoIKgkqPVe8CG9kwMZFeHP+rOOlfep1c3ozhnoiOAqtqRuJxLM1AVcKeiJfbhp0Ezf0uoRFdhbBIVg4Kfx8qG9LLvXhbiKnwOggGL4kYglC0xbohBcZ3yxNyIJHxc+j6CZXlgb48NJt37gu7FSK3QIKgkD1M4a9QUAB8HdNOfY619sIPu4jvkRSRQZf+jHjq6ZbSxCog8rSqjeUkhDv3xta3kyKGT9082rPEQVXggO66nfRn1PIZq21vpNVW5HGPYD+MMti0bMR0MGecx7wtdPgY/NmSP1ZQrY3XUB+1WUuRhtOcTFO+lWWnP98gMXxl9ciR3y1XfWf/m/pQ5bHwkX0p+U32RQXcGujywW5w3zMiCVp8XQLZg4u0RwZnhIFlhRlBqTGJOZtjal/pdw5hKQhTu6e+N0qukrmnqOWKUyWcjKIplwBlApPx6qm+OA/172HUdYXwWy3SMJI6HITNOoTErzvuJamWoj+dXJ+MJf9eTP93k4rTL0GQWkAjCNnzHzx4QsuM9ks9nifPbw2r+FTzQsY3YHZ2hBwHVA35/ciBrTtwJrrK1Oe0k2S48rVaFWWtNV3ZbYAFxpJTrsjkPWtsmFRgvxbTZ+K/+8Nmn7PjA4E58vhJtiRzqNpV387of8TTK7sZfG66jnNFyVhwzAoD4ue2AQ2YOq+U14P4aSs8V+1HxVABL78CIAIKyojQqoXiM=
    WIREGUARD_PRIVATE_KEY: AgA+MIkQrjjs14luUPT0z4+IH2/WBApF+31XG3Pxse69KhFRtmSQTdvV9GwgIX+tmXFmH9jzAsF7utY99lBEuLDaMzVgSjM8PkREmC8pMwLDMilsCMUgNARfSaVShGwESgA6kc0MUFpg4/eQQAmbV7rhrH4wi5U4ogC+0NpDl+RQfs2U2swHSt6o18ASesdDxrc5KYHsPfQTPU4F2iUmYWUiC8YKfE9poVvsmsrbK3Wo/6S710rDDCY1lAVgj8LjV1xKgCXmfcbwHYjvrZubwDjCwwxzIceyjtRKcqWF7tsRf5JWlSkR0I6t/ZmrFNA8zPXcJWteez1fBn4pZNLmbmnWuBO9C9ep9QW2RHQTwFaLy44wTTyEsGWFk38vG7K9BOJU25R3AkkxR1U7AV+IL2nOhlt1G6x0Chp2UXLDZKN/kv/YQC5jDY03Na9jj19XEl5keJ7VDdnrI//NE+7mUEnfOhufW9AYgS+0X3dBEWR8rIEUNlWAgUGrS4ndAxswUelCP7wJ4/2qv+Yxx3e27g2LbC9vBd+igYLuWITJ3qe96Q2Ek5AswnbzhuwndnuTn5YvosNcr1LQ4GzLZOuDD1PCu0VUl/GrrTldGYGxtcbTh0T+2NdvSRbSDzby9HYd789SV7t8WsXoTld3nxS3IyEBnxhEQdgPfq/2R3kLO1M/W8cp/OhELsd4fjlKAVR7LubMr85u+4guHBV/BJ/mJ9PevW+WsZBx+kF88cwXZlPVCyNLRkUPAs5V2Omlrw==
  template:
    metadata:
      name: gluetun-vpn-creds
      namespace: qbittorrent
