---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-vpn-creds
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgAzplywHD87LwU/wj87vIWdiweeMS0bhaURK6Fj5dE5Q3C37C1+QUbVhdgiA99F+bSl0BGad3ovaRlNLiWvic/HNlejCo8L07l7QCtWfiv3+LCXIgrrTQzjgAL5XVVRJDHyoFhTDTeNBvM3/wzkg3nL8Hc6E53BlDxy1MRpU5dGUg5pj2P1Sp84VDNClvofqg2y5DiKKv87T68g3dtAyrMi4bJhM3LsmlpMGXzAiHJVsrafn8HxZXYubPGDJIoykc5haL202kMlD6ejpozg61b3X76p2kPMQ1iQk4laXXNPmMzpO6YJGOowGrpCQiK0jGp6RmmFvvad1hpz08Wg3jCMLmB9dpWTAjWOvNMRl7OUSXytAmwoOpqQvedThpC+hDHqr3pLRA5rM4V5rnIQ7X3tHf9Y/wriBfI9vUfNvZCplTusTSuYSXseTvRvdYoFJIPg2Vbd+V75hr7Ys5Swm/qUHVgVBEUa4p7D1GQCBkVFfpgHk9dXCrtLciFekFrUxH5IRx8AqkyKyZQ0E3mVSDv3E/TkJ+PZzzdMAtOBsQb4oYCCCAexsps6px9ncdXkGmoEqIM3WwLkFlungBczmIzm/eebsBIzw9i59EgV91xDkKZoQTBdkk6oGO7FLXytmw8zB4cTNiHa6xIeoPrVOZli/PXwHeRyeV00u6QX5YSXSzxN7+8JljYrSGbNwVoUpokIVxao9mi38WeA7uciFB4=
    WIREGUARD_PRIVATE_KEY: AgBDR09fM3BgRWsVvR6leaXX5hpxKhNRvHqr6eCZw58jciLhnAtH1sGQahETBHvekr040iv3rPEDcJDvxPGdPsSTurB0TfchfQGRTs9yHXhX8JiL2yaGinnDQM94VLJ0Is8tQjM3Gzk4Avp2hNsGnRSD0YRMnD/mAUQmzRU4QjYR/Cl8BwaYem6CUlkq9heHgluHu4jzYPr2lIDGzfME36SBCOkaVyNdF5I7PUmA1Kipl4yhMmKRfJLasa8XIPDh9c1ibTJNYMrIY7W2NUTl3O0QQK2MjhOVyyS/U4LpO29sLiNkNds0kvyzOhAZfe3FDVIY3Hi1MzUu3vy3hizXJszhJlCHW1i5kTYWew7YrAWThYguMDKl6g2WSrhGLnr7IARh3CJaIpdNgI3VYvmfbCturVvbGtB7/zGt28DMbxnqGDh5L54RP0B+pYZFXGiv5kX5nnffc7czximcKrXi8uBf0v7T77Gm1ZRwQmr3uZQe6p8Ed37JkaFl3Z3+0uQhNPCrf5bMDFLLZFtFKuNbReyHRAxaKyoMN2WsIvlcd6FTT1YvxKSFfZwRrv8v9nSoGletWGVxPw1NTfx/3CdBIfBoLFjEgSV832U1vWgwEUOqM/tD8N+GrEOIcxyR3QOAu1xOLrb040JViizovFYwUZvOJ4FuxUlSpHMsSn2roXATQBDBOXSvaa1zpOnZgj7J8KiudzvWwOVLsnqBlhMXCbViR0gKs6QZE2R+enBVLc5MLfjvTcrl9x6aIqkERw==
  template:
    metadata:
      name: gluetun-vpn-creds
      namespace: qbittorrent
