---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-vpn-creds
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgB0tDrfQo75QeWbfpBupvITmKa7BDhUezVQnn/KULDQn069EZv7u6upOifIt75Tlm7aMiBhkBK93Ny0QDxNRkVlgXmy1/vaYxWzwS0IZ906O8TxNo5EVe+anZI/QvVh1suKZXyyLQ++ffMTijduwh2arKhSdpoIMxXirE6pGWRoo1H2yxZNCdtec+Pm7aMTwHjtKjY5DzYy3YkcJEFiVpvVPNgIMXzzwXgJyXSytR9MpAsno0q/MWxMz6g/kdgNSjWwqk3dMafv2TGvuUGjAhCXRHpEZVLszlFvu3opuGq8GeuoxABUgrVEZ1v+H1fBAve2qWlalq0D6dXBZQyaFvijoevvJhVqTix75c80ozrm9sfNJFz8hLktGfjvxfagEwzukml5ZcCvjHJOciRUqWIFcOI4/Y8Mo/d9gons9D0c5c2mSf+EhaPjNzYrRaAdT2gkZSqUaUjwdpIKN12xbKvz1ihHTdcRwzTaQTjgvZuzVmEco+ExB9kPk2Ye62vngwobKOAR39AdUFLbYtd5jDUBCpklmz0Gzk+vKWyqeS7PEKb+jyevzdLcVOGrYusV/WD+4YgsT8ljG6Qn+WPHXnfqwbQ4fTHm7NG/AL7drVWGh5M11ZVufMDH6grgSWqS8NjkKF3QTs05bZdg8Ty4HDGOw748ke1p4pS3Vi2zgy6DWV1eGW2ZcrzF+23ECYkeV9z5LAyr/kkQ3EiDk++JznIl
    WIREGUARD_PRIVATE_KEY: AgA2QColR9fvGJ2z9vM11EK58tei/tU9TU7nJ+IceaEI0onwrXZfjycdkoDcsT3OIVosQvZJqHbaIHn8s9HRJBN1n9YEVwU7NurvfqKNezjqcUT1mRJ4bZHFSxXoC85fe9y/gcw+0lKMGlBfmyZtvUCH3eRLj8iIZ4o/ftX9FyAY04NI2kiXXfnOYRdQR4Pr5JHavF4LimfaDu8MHbSP71dUPXR0Vy9rETMfjvChyXNgITd52tSOZnIprAiTe7IdlVqqxYESfJns8M1rbKCqEQ+IgLxk3nv+5mX5m+1ZCTB/7WxWIElIrzSLiIg/2s9000FDgAZOiAkojxNek5tFD69E+iP3bS14nYZ/BbT/o2NM7rWn1bFcqxd2B1Q/n8j33E6Ur7TD98IWFnxcgQKBcCKo9H91rMgTmPrl19CdKrORLWE2UYQu/x+FZt/Am8g2Jt7zg1xEpapPAjn+rFqSvMiq/cHU6dC8re2+Uw6qMnhUEpq7sVG7+V7Ub0/KRaPaF90YiTklMNq0Z0MIsErs7lk9EQPG+2KXzyvmvTo0Zz8WCsiOU1ZG5PF/3IEUy67rOHi5Ck/koqqq7dYhiz+WBqT0RXPzo5Hh61XIqhDSNyv6x9r0C3Y3YyWHPEXIWWFEpFTMm2X1pTKkBJoWnVPPP3YyKiUVvQdg+j/8UTNuVghgyFcNJtnYQ3iAQUVJx+sVc2LzcenUwqzFfe975XMxGpY48SFZi5K5c40T+Ma7mTfR5hOuusTDRB/44PjiSA==
  template:
    metadata:
      name: gluetun-vpn-creds
      namespace: qbittorrent
