apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: gluetun-vpn-creds
  namespace: qbittorrent
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /qbittorrent/gluetun-vpn-creds
  targets:
    - name: gluetun-vpn-creds
      namespace: qbittorrent
      kind: Secret
      creationPolicy: Owner
