controllers:
  main:
    pod:
      nodeSelector:
        homelab.io/storage: "true"
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/Los_Angeles
          WEBUI_PORT: "8080"
      gluetun:
        image:
          repository: qmcgaw/gluetun
          tag: latest
        env:
          VPN_SERVICE_PROVIDER: mullvad
          VPN_TYPE: wireguard
          TZ: America/Los_Angeles
          FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8,192.168.0.0/16"
          FIREWALL_INPUT_PORTS: "8080"
          DNS_ADDRESS: "8.8.8.8"
          WIREGUARD_ENDPOINT_PORT: "443"
        envFrom:
          - secretRef:
              name: gluetun-vpn-creds
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

route:
  main:
    enabled: true
    kind: HTTPRoute
    hostnames:
      - qbittorrent.nik-homelab.dev
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        app:
          - path: /config
  data:
    type: nfs
    server: 192.168.30.194
    path: /mnt/storage
    advancedMounts:
      main:
        app:
          - path: /data
