apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: homelab-ef-28
      environmentSlug: prod
      secretPath: /tailscale/operator-oauth
  targets:
    - name: operator-oauth
      namespace: tailscale
      kind: Secret
      creationPolicy: Owner
