---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBYthPQXPRKaOjdXnJsZaRYIza6AA2c9OuYZyEtoc2USiomg8HMcPw8D0fiSEvbReeeSwS4rG5ndDsPT5yDoYfffmLN3E8a/Ei2NHEApDttzjYrhIItFfikxfScYE/ZrwCh6lxs4wr6CkcKETsBEffPFH8ePzmUsuWDu+LCw3/SESTpgaWh+l7bnPTxchd2zP7N+CNZ5jxettOBfZ1toHY2Wp/9YV/knJZSWNMGtLMK7mdMHIBb9wKyaWsXmeudX2KtbXzOMkGRsU68eYNslGFxGDk9/Nxwk7szV9qxsfRTfq9J7LHz0lZgP0GRGaQ9POtOh+G3DvOqivxyebJ8LyZ8YaSpT8LeZ7ifYiGsGtGVD/n81SJ+ZdziSK59mjxsSqkcGWIa4XUKcXqa1pNjtYtmVVqWkGwTgMONIX/qP2UpInDYNoFrmKWUqQMRsO4n37qrVUM1uotFskRbDQNAOKyK8EQYlSt9EzkmO14i+85SrqS64wpnhW7D48MA4u6xya0PL1sRSjUfCky9nc3WiQ4PtwJnP2T3LP9imXVx1DTErKzJ6yqmhs8QgKsvfVm4D8jGZSe5D5dx+jM0QXZtieaqPr+BBvH0RvEfN37emjYiIkuI+7mg9zADhs0nAwmr6m8yAh4LKxBjcHpeRJJibjyNhDcP2q7BZX4mBXQPYK0R1lTjXcy2q1IDC2gQIPLSfmPBkmVlDVFFhDpBEX1I/+L+kg==
    client_secret: AgChVy1Y8kxoUpoN1HgRuLVWf0prRPkU5hFlUU/XL9n1BD/RY77s4xTyM9OjuBbj3UbQf9Uqm3kgbWI1n1bNRinvSCFYQw2l0WawaHI62+fsfDldNIVOsaQ6aB3u7GvhhTMOgcWPz+Opw4qxn68dTSa9btJLRNV2LAS9q047tnH+j3xfLsAzw5Sdmloo7aWBhSL2HXHbh+ODJs2Q/o1DjFl2MsvMb+4HVL2UoDzPrjcDGW/JdjlOR7LS3ev9wJYSflVLSzj4KME7oWW/h0pBVhsrz7+V+bjDow+OHensQZO7d5+FTvDev5bedlKf1GxvrzhdDOsbg9xUCD2M3NA4ooejY1mNo42qDrJ1lBQSh7FN3iysGyPW1yh8Bftlplq1OmmlmCyqz8v2ZBOwP2UnzL+3qsPsgi8uEtftBpixtG2pouWBEkqkfc3OpRNOWoDXQw3abIGiZeh+Mm32Gp9R21YeR5OKOm2qNpBZTT1k35R4ttVSWJA8rYJ70clhecEgzTlNUoRWIi8I1XVutQWwHSjK80YYeTzpfy9UfwtAPmFxt13zmL2BGklCie33q3Mi/s6iTmMD1OB3rJh+U0s+1zk1AZMAO4hOhZzd3SO/I2UlZzXXeHM86AR0K6QKdmpKnCDtm9y6x9jAlQL64TKasOQlwr64y7GAkP5X6C3Mwnf06VMlsndAO22fQxVVRgkY5pAcgob6f7ovA7LjDr6i9PceZcvRe2xAzIse79fGcINiN0kgjO6VSkMzF9OXetJUqBjz0OkS1Jr0uCIZ4rMPqL7S
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
