---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA8F+Zw3OrSa11SjxI6xt+l0PUvfjOozQwXKS1qSSYtzJSBn2cm9uj85wUI231BAOpHwc6I5mhPsy6PQmsgV7wVM9HvQz8EAmng8n4IXmlukazrGoqEPcI8V7aichX19J/TzcHkMZyr4YFa8/NSXV8H7uXN7jpghgejgKgJG6SN8/iZvQVayKvTmlXLKNPQCAwmf+u5KevukZXzxLMdGaJAoG4aF6DBCqpE4YQk1JC3l9hdFOqqR54FtMfKZtc54EQBj6L+u+D6a1J+SzO/jLRMOvjVoboG1z9ahGuxv/6hwUQOHJ4/iB0ScILWSBOSEgeJwjhIB+b4wJW5+MXAzz4yVFB83jwu7aBhdxsdeXqoqHiv+Z3r4sX0wSO0SPeOy6CyyTm6Kmy9Lh+JPePSWaju+cVb+dqaDB1zkC4KvCmEgh9x09aauZFpjVj6KM7iJUorcCwnWQwsm33EKITUhTCPbVZKsD3WaIk50r93N10Q2O2EaMKosRceKplNkbO2F121c4gKLlxsJ9RRVGBJlzbC/0JRR4Y2oBD6x/O5X2oQE4w0jQDmtHTQVrrWRVpZnAWhsaiG2nPbE9L4HXpZe/V94K4aDA5MHWar8ASppXlyTkUMbeE6llWHhwnaUjOEzX+gZh75wZPmqzkahXh1YzgxwipDJSgV0fS2eo8ugf8mra6bcXSE4qZIH1+CwXvs8Vc=
    client_secret: AgAh140JrJoVV6MMpTyOLoSunZ6m8JZa5pOo+t8i+swBY/REKKtEoRf6s4JrZb93Bc05gN+JWT0bwONASwP68/lnPNsrbsGJjmJg/ZTZcjdQD34/RQRHsEgfiCrYMnxgP65VbuTfqh+bKTcvizI/Uf1GUpAWKWRpw48/vRUc9RNmg8UhVB5QAJjjtj61jg9qKmnU6m/fN6pSvQxQAETEVP3l6qJM/82/Biun5xifi+MUi7nksr1uy89JcmCpmDzhbRJDSoF7HudbzeyitrqgqMjnXj44GuHJ4K7KJKj52a3+ZOWUtbt+44LNXSNPQh4qDLEk2TPQWcdj0m7SnsbEbvORFFUai7nTJB2HLcf+jou7EnaR0G3/Y/pRVhXiqKji2jLd5EktSjqQMODXoHKWA1BjAZV6o9bebfkCHPqC4zhKO6+LLcoX1FaoiLwMv/FruJYc9+Zfvobm9COyhchHRtwWFoxBjOK0c+MmvjJSyirM+xT28mLlDil1um1UwyBWhqH7as1eyxfVMM8tljqCeVU9LApzUh6WBRWWT5xCiLoSzXyX0Y6d1d45GooacxP+ZoHQC65+FWR+PypHNNb3G6S9TIlZ9ekJPRZVC66MiRxOhS3B5O0/ahnw7+hfUMuohajNqNMAhMHRb7PZfrqSSyLI0Fw96QtoPwP25d5tP8BxLnrl6ip6AE83/x74c6Q7U6I=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
