---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBComL5CG5OD+rEcFrprX7kOzLlTTP7NuJwHolq4S8isOLmbElviIkm43Sy3a/MKjD0Hi+7cXljMuNbNl1izxVbrwh6xZaHLAe2+HrAcE8Ai4XMlro6Y+BLgDz5WhleB0loZYYYmmU4r6flVv7BOEW7SiRWf21HnhCoaAVBLdlU1JNDoUB7aWS0TH7k1VnqZc3/0upABJibNwGs0TXamjqVwE+h4yFXDxTIPcZgjmYuCvDJoPFYlBTXwjC5UGVIZgjbmnCBXF/psjFEx8eFe/tcMlUa4KZGR06obZZfJtYUiTmhTRSawhaCY8+fVVaWLIlxKJMWhQyQw9G7Xj6b8DDOtidPEPqXqw/TV8LQhqxGQC4jV8ieIKLD/9d63ir4+6pMvUIW09ePMwc7Nsfr4MqdGtoby1x6DijYrmXGnD9qeRHlbS+T2WUKe64I32bvsPfkWKygP/5y+kfbxzDRvEvUwCRE8T2oee/KaZOrrKi211GPfRCfDwPhT4XmIpQdv0TZ8nMkUxvmrdPHBgfHWwMtBOYBDHHmb5tqjYJXPtOGz79QdCotUvjQsJ207K6gqB55PZJhjP5vk+H/Ap7Mc7xcnFU005xhei99NuuaSW9aOvg08i0lYmbVVOux6hiVWqYgPSi/Gjclaxxzcl6TGEt+rZux2dm5m4Hp7FhaJ5FVI7uIzzDZnvoXuoGE/+QvwA4=
    client_secret: AgBTVUM3ZJHxiogzXSoJHjcCUUTe8YMYfV+bQJjUdYoQSKWmvMafQYOuIpAZ2sf5Vk+2BKttvscRprBgfcJelPulMAKbEVIjWUxOEMR6zCnk+x0ADtKeiNNhNoM94FabrAbTdemtVDlbCuSOuYrfxgFcbfw//IkxvewOTuiDwV1zhuMfRvj2pOkETLjGUTy29U5sjmdbrCDT294SFwmrZmD5zy0xJgnZpXksc9wufIihVrECvV3u4Fm8Dq8m7cNYU+6nmqc/XXtP3iTBEsZ4Yq/IWdU5BNoVkw0/d3bnqERIt3jSPpWkJaWH1DOfuCEc1IApCbn0UJPv66zEjAKX8ZtxlRSal4rOcfeh3l70GUWWZTn0ESvvf1mwsU4E5WLhoiacUgIzrUbrlKxc7wL8dGJ+Q/0mtldAmjpYYBcc0Gn5EBCXQZaW6JTTRz/qojD+2mnxDRC+5h9qltEu1NKiO1yFcg6HbfJWuDiSFvVz7EKTHkTusmA5cmziBAZmjRg0VAgSzUX5kQsayK4KXOAcavg7nBJc62EaYVvPkcIYLqBN0CNQaKtt9CZQ2+7gzR184ZcC2+mKYopVAH0+P5T4NlnHkH0H6VnxMA37N4hGP7lYdvoyOmSfkarmto6YsaGZUSv/08dshWIfGWzHaDnXTZe5AyY6BtTZYTej4pM/FLo7QyekDWrRIqQeN6L9exZhFnE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
