---
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: k3s.orchestration
    source: https://github.com/k3s-io/k3s-ansible
    type: git
    version: "1.2.1"
  - name: community.general
